# render.yml

services:
  - type: web
    plan: free
    name: fmdb-api-backend
    env: node
    nodeVersion: 18.x
    buildCommand: npm install
    startCommand: node server.js
    
    healthCheckPath: /
    autoDeploy: true
    instanceType: free




    